spring:
  data:
    redis:
      host: 192.168.237.129
      port: 6379
#      数据库索引
      database: 0
      timeout: 10000
      lettuce:
        pool:
      #连接池最大连接数（使用负值表示没有限制）
          max-active: 20
      #最大阻塞等待时间(负数表示没限制)
          max-wait: -1
      #连接池中的最大空闲连接
          max-idle: 5
      #连接池中的最小空闲连接
          min-idle: 0

